spring:
  datasource:
    url: jdbc:mysql://47.105.177.77:3306/springboot?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gaosheng
  session:
    store-type: none
  redis:
    host: 47.105.177.77
    port: 6379
    password: gaosheng
security:
  basic:
    enabled: true
#andy:
# security:
#   browser:
#     loginPage: /demo-sign.html
andy:
  security:
    browser:
      loginType: JSON
    code:
      image:
        length: 6
        width: 100 # 验证码参数可配置
        url: