spring:
  datasource:
    url: jdbc:mysql://47.105.177.77:3306/admin_pro?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gaosheng
  session:
    store-type: none
  redis:
    host: 47.105.177.77
    port: 6379
    password: gaosheng
security:
  basic:
    enabled: true
#andy:
# security:
#   browser:
#     loginPage: /demo-sign.html
andy:
  security:
    browser:
      loginType: JSON
      signPage: /demo-sginUp.html
    code:
      image:
        length: 6
        width: 100 # 验证码参数可配置
        url:
      sms:
        url:

    social:
      filterProcessUrl: /qqLogin

      qq:
        app-id: 100550231 #101386962
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        #
        #
server:
  port: 8040